modLoader="javafml"
loaderVersion="[47,48)"
license="All-Rights-Reserved"

[[mods]]
modId="invisiblekeybinding"
version="${mod_version}"
displayName="InvisibleKeybinding"
description='''
Client-side utility tweaks.
'''
authors="Tapio, TuYw"

[[dependencies.invisiblekeybinding]]
modId="forge"
mandatory=true
versionRange="[47,48)"
ordering="NONE"
side="CLIENT"

[[dependencies.invisiblekeybinding]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
